export const CAREERS_TRAPPINGS = {
  Abbess: ['Abbey', 'Library (Theology)'],
  Advisor: ['Livery'],
  Agent: [
    'Book (Cryptography)',
    'Ring of Spies and Informers',
    'Loft of Homing Pigeons',
    'Quill and Ink',
  ],
  Agitator: ['Leather Jack'],
  Aide: ['Writing Kit'],
  Ambassador: [
    'Aide',
    'Best Quality Courtly Clothes',
    'Sta? of Diplomats',
    'Herald',
  ],
  Apothecary: ['Guild License', 'Trade Tools'],
  'Apothecary-General': ['Commission Papers', 'Large Workshop'],
  "Apothecary's Apprentice": [
    'Book (Blank)',
    'Healing Draught',
    'Leather Jerkin',
    'Pestle and Mortar',
  ],
  'Apprentice Artisan': ['Chalk', 'Leather Jerkin', 'd10 rags'],
  'Apprentice Artist': ['Brush or Chisel or Quill Pen'],
  Artisan: ['Guild License', 'Trade Tools'],
  Artist: ['Sling Bag containing Trade Tools (Artist)'],
  Assassin: ['Crossbow with 10 shots', 'Disguise Kit'],
  Attendant: ['Quality Livery', 'Storm Lantern', 'Tinderbox', 'Lamp Oil'],
  Bailiff: ['Leather Jack', '3 Tax Collectors'],
  'Bandit King': ["'Fiefdom' of Outlaw Chiefs", 'Lair'],
  'Barge Master': ['Hat', 'Riverboat and Crew'],
  Bargeswain: ['Backpack', 'Trade Tools (Carpenter)'],
  Barrister: ['Office', 'Assistant (Student or Servant)'],
  Bawd: ['Dose of Weirdroot', 'Quality Clothing'],
  Beggar: ['Crutch', 'Bowl'],
  'Beggar King': ['Lair', 'Large Group of Beggar Followers'],
  'Black Marketeer': ['Hired Muscle', 'Network of Informants', 'Warehouse'],
  'Boat-hand': ['Hand Weapon (Boat Hook)', 'Leather Jack', 'Pole'],
  Boatman: ['Rope', 'Rowboat'],
  Boatswain: ['Trade Tools (Carpenter)'],
  'Body Snatcher': ['Crowbar', 'Handcart', 'Hooded Cloak', 'Tarpaulin'],
  'Bounty Hunter': [
    'Crossbow and 10 bolts',
    'Leather Skullcap',
    'Manacles',
    'Net',
    'Warrant Papers',
  ],
  'Bounty Hunter General': [
    'Draught Horse and Cart',
    'Mail Shirt',
    '4 Pairs of Manacles',
  ],
  Braggart: ['Hood or Mask', 'Knuckledusters', 'Leather Jack'],
  Brigand: ['Bedroll', 'Hand Weapon', 'Leather Jerkin', 'Tinderbox'],
  Broker: ['Hand Weapon', 'Stolen Goods worth 3d10 Shillings'],
  Burgomeister: [
    'Chains of Office',
    'Coach and Footman',
    'Quality Clothing',
    'Large Townhouse with Gardens and Servants',
  ],
  Busker: ['Bowl', 'Instrument'],
  'Cargo Scavenger': ['Crowbar', 'Large Sack', 'Leather Gloves'],
  'Cat Burglar': ['Dark Clothing', 'Grappling Hook', 'Mask or Scarves'],
  Cavalryman: [
    'Breastplate',
    'Helmet',
    'Light Warhorse with Saddle and Tack',
    'Pistol with 10 Shots',
    'Shield',
  ],
  Chancellor: [
    'Riding Horse with Saddle and Harness',
    'Quality Courtly Garb',
    'Sta? of Advisors and Aides',
  ],
  Charlatan: [
    '1 Forged Document',
    '2 Sets of Quality Clothing',
    'Selection of Colored Powders and  Water',
    'Selection of Trinkets and Charms',
  ],
  'Chartered Engineer': [
    'Guild License',
    'Library (Engineer)',
    'Quality Trade Tools (Engineer)',
    'Large Workshop (Engineer)',
  ],
  Clerk: ['Lodgings', 'Sturdy Boots'],
  'Coach Master': ['Mail Shirt', 'Pistol', 'Quality Cloak'],
  Coachman: ['Blunderbuss with 10 Shots', 'Coach Horn', 'Leather Jack', 'Hat'],
  'Con Artist': ['Disguise Kit', 'Lock Picks', 'Multiple Forged Documents'],
  Councilor: ['Mule and Cart', 'Village Home and Workshop'],
  Counsellor: ['Quality Clothing', 'Aide'],
  Courier: ['Backpack', 'Saddlebags', 'Shield'],
  'Courier-Captain': ['Couriers', 'Mail Shirt', 'Writing Kit'],
  'Court Physician': ['Courtly Attire', 'Letter of Appointment'],
  'Crime Lord': [
    'Network of Informers',
    'Quality Clothing and Hat',
    'Subordinate Gang Bosses',
  ],
  Custodian: ['Keys', 'Lantern', 'Lamp Oil', 'Livery'],
  'Daemon Slayer': ["Dragon's Head"],
  Demagogue: ['3 Pamphleteers', 'Patron', 'Printing Press', 'Impressive Hat'],
  Detective: ['Network of Informants', 'Spyglass'],
  Diplomat: ['Aide', 'Quality Clothes', 'Map'],
  'Dock Master': ['Office and Sta?', 'Writing Kit'],
  Dockhand: ['Hand Weapon (Boat Hook)', 'Leather Gloves'],
  Doktor: ['Apprentice', 'Workshop (Medicine)'],
  'Dragon Slayer': ["Giant's Head", 'Throwing Axes'],
  Duellist: [
    'Main Gauche or Sword-breaker',
    'Pistol with Gunpowder and Ammunition',
  ],
  Duelmaster: [
    'Quality Rapier',
    'Hand Weapon',
    'Trusty Second',
    '2 Wooden Training Swords',
  ],
  Engineer: ['Guild License', 'Trade Tools'],
  Entertainer: [
    'Costume',
    'Instrument',
    "Selection of Scripts (that you can't yet read)",
    'Throwing Weapons',
  ],
  Envoy: ['Quill and Ink', '10 sheets of parchment'],
  Explorer: ['Selection of Maps', 'Trade Tools (Cartographer)'],
  Exterminator: [
    'Assistant',
    'Large and Vicious Dog',
    'Sack of Poisoned Bait (10 doses of Heartkill)',
  ],
  Fellow: ['Mortarboard', 'Robes'],
  Fence: ['Eye-glass', 'Trade Tools (Engraver)', 'Writing Kit'],
  Fencer: [
    'Hand Weapon or Rapier',
    'Sling Bag containing Clothing and 1d10 Bandages',
  ],
  'First Knight': ['Barding', 'Small Unit of Knights'],
  Flagellant: ['Placard', 'Religious Symbol', 'Sling'],
  Foreman: ['Gang of Stevedores', 'Whistle'],
  'Fortune Teller': ['Deck of Cards or Dice', 'Cheap Jewelry'],
  'Gang Boss': [
    'Crossbow Pistol with 10 Bolts',
    'Gang of Thugs and Racketeers',
    'Lair',
  ],
  'Giant Slayer': ['Great Axe', 'Jewelry', "Troll's Head"],
  Governor: ['Aide', "Governor's Residence", 'Servant'],
  'Grave Robber': ['Backpack', 'Hand Weapon', 'Spade', 'Storm Lantern and Oil'],
  Greenfish: ['Bucket', 'Fishing Rod and Bait', 'Leather Leggings'],
  Guard: ['Bow with 10 Arrows', 'Sleeved Mail Shirt', 'Shield', 'Spear'],
  'Guard Officer': ['Breastplate'],
  Guide: ['Hand Weapon', 'Leather Jack', 'Sturdy Boots and Cloak', 'Rope'],
  Guildmaster: ['Guild', 'Quality Clothing'],
  'Hedge Apprentice': ['1d10 Lucky Charms', 'Quartersta?', 'Backpack'],
  'Hedge Master': ['Isolated Hut', 'Apprentice'],
  'Hedge Witch': [
    'Antitoxin Kit',
    'Healing Poultice',
    'Trade Tools (Herbalist)',
  ],
  Hedgewise: ['Assortment of Animal Skulls', 'Ceremonial Cloak and Garland'],
  Herald: ['Leather Jack', 'Livery', 'Scroll Case'],
  'Herb Gatherer': [
    'Boots',
    'Cloak',
    'Sling Bag containing Assortment of Herbs',
  ],
  'Herb Master': [
    'Herb Gatherer',
    '3 Healing Poultices',
    'Healing Draught',
    'Workshop (Herbalist)',
  ],
  Herbalist: [
    'Hand Weapon (Sickle)',
    'Healing Poultice',
    'Trade Tools (Herbalist)',
  ],
  Herbwise: ['Pony and Cart'],
  Hexer: ['Candles', 'Chalk', 'Doll', 'Pins'],
  'High Priest': [
    'Quality Robes',
    'Religious Relic',
    'Subordinate Priests',
    'Temple',
  ],
  Hitman: ['Cloak', 'Garotte', 'Poison', 'Throwing Knives'],
  'Honor Guard': ['Great Weapon or Halberd', 'Helmet', 'Uniform'],
  Horseman: ['Leather Jack', 'Riding Horse with Saddle and Tack'],
  Huffer: ['Leather Jerkin', 'Rope', 'Row Boat'],
  Hunter: ['Bow with 10 arrows'],
  Huntsmaster: ['Riding Horse with Saddle and Tack', 'Kennel of Hunting Dogs'],
  Hustler: ['Flask of Spirits'],
  Informer: [
    'Charcoal stick',
    'Sling Bag containing 2 different sets of clothing and Hooded Cloak',
  ],
  Initiate: ['Religious Symbol', 'Robes'],
  Inquisitor: ['Quality Clothing', 'Subordinate Interrogators'],
  Interrogator: ['Hand Weapon', 'Instruments of Torture'],
  Investigator: ['Leather Jack', 'Hand Weapon', 'Magnifying Glass', 'Lockpick'],
  Judge: ['Gavel', 'Ostentatious Wig'],
  'Judicial Champion': ['2 Quality Weapons'],
  Knight: [
    'Destrier with Saddle and Tack',
    'Melee Weapon (Any)',
    'Lance',
    'Plate Armor and Helm',
  ],
  'Knight of the Inner Circle': [
    'Plumed Great Helm',
    'Squire',
    'Large Unit of Knights or Several Small Units of Knights',
  ],
  Landsman: ['Bucket', 'Brush', 'Mop'],
  Lawyer: ['Court Robes', 'Guild License', 'Writing Kit'],
  Lector: ['Library (Theology)', 'Subordinate High Priests'],
  'Light Cavalry Officer': ['Deck of Cards', 'Quality Clothing'],
  'Light Cavalry Sergeant': ['Sash'],
  Maestro: ['Large Workshop (Artist)', 'Library (Art)', '3 Apprentices'],
  Magistrate: ['Library (Law)', 'Quality Robes', 'Seal of Office'],
  Magnate: [
    '2 sets of Quality Courtly Garb',
    '200 GC',
    'Fiefdom',
    'Jewelry worth 200 GC',
    'Signet Ring',
  ],
  'Master Apothecary': ['Book (Apothecary)', 'Apprentice', 'Workshop'],
  'Master Artisan': ['Apprentice', 'Workshop'],
  'Master Artist': ['Apprentice', 'Patron', 'Workshop (Artist)'],
  'Master Beggar': ['Disguise Kit', 'Hiding Place', 'Pauper Follower'],
  'Master Bounty Hunter': ['Mail Shirt', 'Riding Horse and Saddle'],
  'Master Engineer': ['Workshop'],
  'Master Fence': ["Pawnbroker's Shop"],
  'Master Investigator': ['Assistant', 'Office'],
  'Master Merchant': ['Town House with Servants', 'Warehouse', '100 GC'],
  'Master Miner': [
    'Great Weapon (Two-handed Pick)',
    'Helmet',
    'Trade Tools (Engineer)',
  ],
  'Master Pedlar': ['Cart', 'Goods worth at least 2d10 Gold'],
  'Master Pilot': ['Boathand', 'Small Riverboat'],
  'Master Smuggler': ['River Runner', 'Speedy Riverboat'],
  'Master Thief': ['Crossbow Pistol with 10 Bolts'],
  'Master Wizard': ['Apprentice', 'Light Warhorse', 'Magical Item'],
  Menial: ['Floor Brush'],
  Merchant: ['Riverboat or 2 Wagons', 'Guild License', '20 GC'],
  'Merchant Prince': [
    '2 Riverboats or 4 Wagons',
    'Large Town Estate',
    '2 Warehouses',
    '1000 GC',
    'Quality Clothing',
  ],
  Messenger: [
    'Hand Weapon',
    'Leather Jack',
    'Riding Horse with Saddle and Tack',
  ],
  'Mine Foreman': ['Crew of Miners', 'Writing Kit'],
  Miner: ['Davrich Lamp', 'Hand Weapon (Pick)', 'Lamp Oil', 'Leather Jack'],
  Mystic: ['Selection of Amulets'],
  Noble: [
    '4 Household Servants',
    'Quality Courtly Garb',
    'Courtly Garb',
    'Riding Horse with Saddle and  Harness or Coach',
    'Main Gauche or Quality Cloak',
    'Jewelry worth 50 GC',
  ],
  'Noble Lord': [
    '4 sets of Best Quality Courtly Garb',
    'Quality Foil or Hand Mirror',
    '500 GC',
    'Jewelry worth 500 GC',
    'Province',
  ],
  'Novitiate (Nun)': ['Religious Symbol', 'Robes'],
  'Novitiate (Warrior Priest)': [
    'Book (Religion)',
    'Leather Jerkin',
    'Religious Symbol',
    'Robes',
    'Weapon (Any Melee)',
  ],
  Nun: ['Book (Religion)', 'Religious Relic', 'Trade Tools (Any)'],
  Officer: [
    'Letter of Commission',
    'Light Warhorse with Saddle and Tack',
    'Map',
    'Orders',
    'Unit of  Soldiers',
    'Quality Uniform',
    'Symbol of Rank',
  ],
  Outlaw: ['Bow with 10 Arrows', 'Shield', 'Tent'],
  'Outlaw Chief': [
    'Helmet',
    'Riding Horse with Saddle and Tack',
    'Sleeved Mail Shirt',
    'Band of Outlaws',
  ],
  Pamphleteer: ['Writing Kit', 'Hammer and Nails', 'Pile of Leaflets'],
  Pathfinder: [
    'Map',
    'Riding Horse with Saddle and Tack',
    "Saddlebags with 2 weeks' Rations",
    'Tent',
  ],
  Pauper: ['Poor Quality Blanket', 'Cup'],
  Peasant: ['None'],
  Pedlar: [
    'Mule and Saddlebags',
    'Goods worth 2d10 Silver',
    'Selection of Pots and Pans',
    'Trade Tools (Tinker)',
  ],
  Penitent: ['Religious Relic'],
  Physician: ['Book (Medicine)', 'Guild License', 'Trade Tools (Medicine)'],
  "Physician's Apprentice": ['Bandages', 'Healing Draught'],
  Pilot: ['Pole', 'Storm Lantern and Oil'],
  'Pit Champion': ['Breast Plate', 'Helmet'],
  'Pit Fighter': [
    'Flail or Great Weapon',
    'Hand Weapon',
    'Net or Whip',
    'Shield or Buckler',
  ],
  'Pit Legend': ['Quality Helmet'],
  Postilion: ['Warm Coat and Gloves', 'Whip'],
  Priest: ['Book (Religion)', 'Ceremonial Robes'],
  'Priest Captain': ['Religious Relic'],
  'Priest Sergeant': ['Light Warhorse with Saddle and Tack'],
  'Prioress General': ['Religious Order'],
  Procurer: ['A Ring of Hustlers'],
  Professor: ['Study'],
  'Prophet of Doom': [
    'Book (Religion)',
    'Followers (including Penitents',
    'Flagellants',
    'and Zealots)',
  ],
  Prospector: ['Charcoal Stick', 'Crude Map', 'Pan', 'Spade'],
  Protagonist: [
    'Hand Weapon',
    'Mail Shirt',
    'Riding Horse with Saddle and Tack',
    'Shield',
  ],
  Prowler: ['Crowbar', 'Leather Jerkin', 'Sack'],
  Pugilist: ['Bandages', 'Knuckledusters', 'Leather Jack'],
  'Rabble Rouser': ['Hand Weapon', 'Pamphleteer'],
  Racketeer: ['Hand Weapon', 'Hat', 'Mail Shirt'],
  'Rat Catcher': ['Animal Traps', 'Pole for Dead Rats'],
  'Rat Hunter': ['Sling with Ammunition', 'Sack', 'Small but Vicious Dog'],
  Recruit: ['Dagger', 'Leather Breastplate', 'Uniform'],
  Reeve: ['Horse with Saddle and Tack', 'Breastplate', 'Baili?'],
  Ringleader: ['Townhouse with Discreet Back Entrance', 'a Ring of Bawds'],
  'River Elder': ['Hut or Riverboat'],
  'River Pirate': [
    'Crossbow with 10 Bolts',
    'Grappling Hook and Rope',
    'Riverboat',
  ],
  'River Recruit': ['Hand Weapon (Sword)', 'Leather Jack', 'Uniform'],
  'River Runner': [
    'Large Sack',
    'Mask or Scarves',
    'Tinderbox',
    'Storm Lantern and Oil',
  ],
  Riverguide: ['Hand Weapon (Boat Hook)', 'Storm Lantern and Oil'],
  Riverwarden: ['Lantern and Oil', 'Pistol with 10 shot', 'Shield'],
  Riverwise: ['Row Boat', 'Storm Lantern and Oil'],
  Riverwoman: ['Eel Trap', 'Leather Jerkin', 'Net', 'Spear'],
  'Road Captain': [
    'Light Warhorse',
    'Pistol with 10 Shots',
    'Quality Hat and Cloak',
    'Unit of Road Wardens',
  ],
  'Road Sergeant': [
    'Squad of Road Wardens',
    'Pistol with 10 Shots',
    'Shield',
    'Symbol of Rank',
  ],
  'Road Warden': [
    'Hand Weapon',
    'Mail Shirt',
    'Riding Horse with Saddle and Harness',
    'Rope',
  ],
  'Route Master': ['Fleet of Coaches and Horses', 'Maps'],
  Runner: ['Scroll Case'],
  Sage: ['Trade Tools (Writing)'],
  Scholar: ['Access to a Library', 'Degree'],
  Scion: [
    'Courtly Garb',
    'Foil or Hand Mirror',
    'Jewelry worth 3d10 GC',
    'Personal Servant',
  ],
  Scoundrel: ['Forged Seal', 'Writing Kit'],
  Scout: ['Bow and 10 Arrows', 'Mail Shirt'],
  Seaman: ['Hand Weapon (Boat Hook)', 'Leather Jerkin'],
  Seer: ['Trade Tools (Astrology)'],
  Seneschal: [
    'Breastplate',
    'Ceremonial Staff of Office',
    'Staff of Wardens and Custodians',
  ],
  Sentry: ['Buckler', 'Leather Jerkin', 'Storm Lantern with Oil'],
  Sergeant: ['Symbol of Rank', 'Unit of Troops'],
  Servant: ['Livery'],
  'Sewer Jack': ['Davrich Lantern', 'Hand Weapon', 'Leather Jack'],
  "Ship's Master": [
    'Shipping Charts',
    'Sailing Ship and Crew',
    'Sextant',
    'Spyglass',
  ],
  Shipsword: ['Grappling Hook', 'Helmet', 'Mail Shirt'],
  'Shipsword Master': ['Patrol Boats and Crew', 'Symbol of Rank'],
  Sleuth: ['Lantern', 'Lamp Oil', 'Journal', 'Quill and Ink'],
  Smuggler: ['2 Barrels', 'Hand Weapon', 'Leather Jack', 'Row Boat'],
  'Smuggler King': ['Disguise Kit', 'Small Fleet of Riverboats'],
  Soldier: ['Breastplate', 'Helmet', 'Weapon (Any)'],
  Spy: [
    'Informer',
    'Hand Weapon',
    'Disguise Kit',
    'Ring of Informers',
    'Telescope',
  ],
  Spymaster: [
    'Office and Staff',
    'Large Spy Ring of Agents',
    'Spies',
    'and Informers',
  ],
  Squire: [
    'Leather Jack',
    'Mail Shirt',
    'Riding Horse with Saddle and Tack',
    'Shield',
    'Trade Tools (Farrier)',
  ],
  Stevedore: [
    'Guild License',
    'Leather Jerkin',
    'Pipe and Tobacco',
    'Porter Cap',
  ],
  Steward: ['Hand Weapon', 'Fine Clothes', 'Servant'],
  Student: ['Alcohol', 'Book', 'Opinions', 'Writing Kit'],
  'Student Engineer': ['Book (Engineer)', 'Hammer and Spikes'],
  'Student Lawyer': ['Book (Law)', 'Magnifying Glass'],
  Swindler: ['Backpack', '2 Sets of Clothing', 'Deck of Cards', 'Dice'],
  'Tax Collector': ['Hand weapon', 'small lock box'],
  Thief: ['Trade Tools (Thief)', 'Rope'],
  'Thief-taker': ['Hand Weapon', 'Leather Jerkin', 'Rope'],
  Thug: ['Knuckledusters', 'Leather Jack'],
  'Toll Keeper': ['Crossbow with 10 Bolts', 'Leather Jack'],
  'Tomb Robber': [
    'Hand Weapon (Pick)',
    'Horse and Cart',
    'Leather Jack',
    'Rope',
    'Trade Tools (Thief)',
  ],
  'Town Councilor': ['Coach and Driver', 'Townhouse'],
  Townsman: ['Modest Townhouse', 'Servant', 'Quill and Ink'],
  Tracker: ['Backpack', 'Bedroll', 'Ten'],
  Trader: [
    'Abacus',
    'Mule and Cart',
    'Canvas Tarpaulin',
    '3d10 Silver Shillings',
  ],
  Trapper: [
    'Selection of Animal Traps',
    'Hand Weapon',
    'Sturdy Boots and Cloak ',
    'Sling with (10 Stone Bullets)',
  ],
  'Treasure Hunter': [
    'Bedroll',
    'Maps',
    'Tent',
    'Trade Tools (Engineer)',
    'Writing Kit',
  ],
  'Troll Slayer': ['Axe', 'Flask of Spirits', 'Shame', 'Tattoos'],
  Troubadour: ['Trained Animal', 'Writing Kit'],
  'Troupe Leader': [
    'Draught Horses and Wagon (Stage)',
    'Wardrobe of Costumes and Props',
    'Troupe of Entertainers',
  ],
  Vagabond: ['Backpack', 'Bedroll', 'Goods worth 2d10 Brass', 'Tent'],
  'Village Elder': ['The Respect of the Village'],
  Villager: ['Leather Jerkin', 'Hand Weapon (Axe)', 'Trade Tools (as Trade)'],
  'Wandering Trader': [
    'Draught Horse and Wagon',
    'Goods worth at least 5d10 Gold',
    '50 Silver in Coin',
  ],
  Warden: [
    'Hand Weapon or Bow with 10 arrows',
    'Riding Horse with Saddle and Harness',
    'Leather Jack',
  ],
  Warlock: ['Robes', 'Skull'],
  'Warrior Priest': ['Breastplate', 'Weapon (Any)'],
  'Watch Captain': [
    'Riding Horse with Saddle and Tack',
    'Quality Hat',
    'Quality Hand weapon',
    'Quality Symbol of Rank',
  ],
  'Watch Recruit': ['Hand Weapon', 'Leather Jack', 'Uniform'],
  'Watch Sergeant': ['Breastplate', 'Helm', 'Symbol of Rank'],
  Watchman: ['Lantern and Pole', 'Lamp Oil', 'Copper Badge'],
  Witch: [
    'Quartersta?',
    'Sack',
    'Selection of Herbs',
    'Trade Tools (Herbalist)',
  ],
  'Witch Hunter': [
    'Crossbow Pistol or Pistol',
    'Hat (Henin)',
    'Leather Jack',
    'Riding Horse with Saddle and Tack',
    'Rope',
    'Silvered Sword',
  ],
  'Witchfinder General': [
    'Best Quality Courtly Garb',
    'Subordinate Witch Hunters',
  ],
  Wizard: ['Magical License'],
  'Wizard Lord': ['Apprentice', 'Library (Magic)', 'Workshop (Magic)'],
  "Wizard's Apprentice": ['Grimoire', 'Staff'],
  Wrecker: ['Hand Weapon (Boat Hook)', 'Leather Jack', 'Storm Lantern and Oil'],
  'Wrecker Captain': [
    'Fleet of Riverboats and Wrecker Crew',
    'Keg of Ale',
    'Manacles',
  ],
  Wyrd: ['Backpack', 'Cloak with Several Pockets', 'Lucky Charm'],
  Zealot: ['Flail', 'Tattered Robes'],
};
