export const traitPrefix = '@Trait - ';
export const psychologyPrefix = '@Psy - ';
export const randomTalent = '@RndTal - ';
export const origin = '@Origin';

export const speciesSkills = {
  ogre: [
    'Consume Alcohol',
    'Cool',
    'Endurance',
    'Gamble',
    'Intimidate',
    'Language (Any)',
    'Language (Grumbarth)',
    'Language (Mootish)',
    'Lore (Ogres)',
    'Melee (Basic)',
    'Melee (Brawling)',
    'Trade (Cook)',
  ],
  human: [
    'Animal Care',
    'Charm',
    'Cool',
    'Evaluate',
    'Gossip',
    'Haggle',
    'Language (Bretonnian)',
    'Language (Wastelander)',
    'Leadership',
    'Lore (Reikland)',
    'Melee (Basic)',
    'Ranged (Bow)',
  ],
  dwarf: [
    'Consume Alcohol',
    'Cool',
    'Endurance',
    'Entertain (Storytelling)',
    'Evaluate',
    'Intimidate',
    'Language (Khazalid)',
    'Lore (Dwarfs)',
    'Lore (Geology)',
    'Lore (Metallurgy)',
    'Melee (Basic)',
    'Trade (any one)',
  ],
  halfling: [
    'Charm',
    'Consume Alcohol',
    'Dodge',
    'Gamble',
    'Haggle',
    'Intuition',
    'Language (Mootish)',
    'Lore (Reikland)',
    'Perception',
    'Sleight of Hand',
    'Stealth (Any)',
    'Trade (Cook)',
  ],
  helf: [
    'Cool',
    'Entertain (Sing)',
    'Evaluate',
    'Language (Eltharin)',
    'Leadership',
    'Melee (Basic)',
    'Navigation',
    'Perception',
    'Play (any one)',
    'Ranged (Bow)',
    'Sail (any one)',
    'Swim',
  ],
  welf: [
    'Athletics',
    'Climb',
    'Endurance',
    'Entertain (Sing)',
    'Intimidate',
    'Language (Eltharin)',
    'Melee (Basic)',
    'Outdoor Survival',
    'Perception',
    'Ranged (Bow)',
    'Stealth (Rural)',
    'Track',
  ],
  gnome: [
    'Channelling (Ulgu)',
    'Charm',
    'Consume Alcohol',
    'Dodge',
    'Entertain (Any)',
    'Gossip',
    'Haggle',
    'Language (Ghassally)',
    'Language (Magick)',
    'Language (Wastelander)',
    'Outdoor Survival',
    'Stealth (Any)',
  ],
};

export const speciesOthers = {
  ogre: [
    'Acute Sense (WFRP4NPCGEN.smell), Acute Sense (WFRP4NPCGEN.taste)',
    'Resistance (Mutation), Strong-minded',
    'Night Vision',
    'Very Resilient, Very Strong',
    `${traitPrefix}Bite`,
    `${traitPrefix}Size (Large)`,
    `${psychologyPrefix}Ogre Hunger`,
    `${psychologyPrefix}Favorite Snack (any one)`,
    origin,
    0,
  ],
  human: ['Doomed', 'Savvy, Suave', 3],
  dwarf: [
    'Magic Resistance',
    'Night Vision',
    'Read/Write, Relentless',
    'Resolute, Strong-minded',
    'Sturdy',
    0,
  ],
  halfling: [
    'Acute Sense (WFRP4NPCGEN.taste)',
    'Night Vision',
    'Resistance (Chaos)',
    'Small',
    2,
  ],
  helf: [
    'Acute Sense (WFRP4NPCGEN.sight)',
    'Coolheaded, Savvy',
    'Night Vision',
    'Second Sight, Sixth Sense',
    'Read/Write',
    0,
  ],
  welf: [
    'Acute Sense (WFRP4NPCGEN.sight)',
    'Hardy, Second Sight',
    'Night Vision',
    'Read/Write, Very Resilient',
    'Rover',
    0,
  ],
  gnome: [
    'Beneath Notice, Suffused with Ulgu',
    'Luck, Mimic',
    'Night Vision',
    'Fisherman, Read/Write',
    'Second Sight, Sixth Sense',
    'Small',
    0,
  ],
};

export const subSpeciesSkills = {
  human: {
    'averlander-nom': [
      'Animal Care',
      'Charm Animal',
      'Entertain (Speeches)',
      'Gossip',
      'Language (Bretonnian)',
      'Language (Khazalid)',
      'Language (Mootish)',
      'Leadership',
      'Lore (Averland)',
      'Melee (Basic)',
      'Ride (Horse)',
      'Trade (Farmer)',
    ],
    'hochlander-nom': [
      'Animal Care',
      'Charm',
      'Cool',
      'Haggle',
      'Lore (Hochland)',
      'Melee (Basic)',
      'Outdoor Survival',
      'Perception',
      'Ranged (Bow)',
      'Ranged (Blackpowder)',
      'Secret Signs (Hunters)',
      'Stealth (Rural)',
      'Track',
    ],
    'ostermarker-nom': [
      'Consume Alcohol',
      'Cool',
      'Endurance',
      'Haggle',
      'Intimidate',
      'Intuition',
      'Language (Gospodarinyi)',
      'Language (Ungol)',
      'Leadership',
      'Lore (Ostermark)',
      'Melee (Basic)',
      'Melee (Polearm)',
      'Ranged (Bow)',
    ],
    'ostlander-nom': [
      'Cool',
      'Endurance',
      'Gamble',
      'Intimidate',
      'Language (Gospodarinyi)',
      'Language (Ungol)',
      'Lore (Ostland)',
      'Melee (Basic)',
      'Navigation',
      'Outdoor Survival',
      'Sail (any one)',
      'Swim',
    ],
    'stirlander-nom': [
      'Bribery',
      'Cool',
      'Evaluate',
      'Gossip',
      'Haggle',
      'Language (Mootish)',
      'Leadership',
      'Lore (Stirland)',
      'Melee (Basic)',
      'Ranged (Bow)',
      'Sleight of Hand',
      'Stealth (Rural)',
      'Stealth (Urban)',
    ],
    'sylvanian-nom': [
      'Animal Care',
      'Athletics',
      'Charm Animal',
      'Charm',
      'Cool',
      'Endurance',
      'Lore (Sylvania)',
      'Lore (Undead)',
      'Lore (Vampires)',
      'Melee (Basic)',
      'Melee (Polearm)',
      'Outdoor Survival',
      'Stealth (Rural)',
    ],
    'talabeclander-nom': [
      'Animal Care',
      'Charm Animal',
      'Cool',
      'Gossip',
      'Haggle',
      'Lore (Talabecland)',
      'Melee (Basic)',
      'Navigation',
      'Outdoor Survival',
      'Perception',
      'Ranged (Bow)',
      'Track',
    ],
    'wissenlander-nom': [
      'Animal Care',
      'Cool',
      'Endurance',
      'Haggle',
      'Intuition',
      'Language (Bretonnian)',
      'Language (Estalian)',
      'Language (Tilean)',
      'Leadership',
      'Lore (Wissenland)',
      'Melee (Basic)',
      'Ranged (Blackpowder)',
      'Trade (Farmer)',
      'Trade (Miner)',
    ],
    'albionite-nom': [
      'Athletics',
      'Climb',
      'Cool',
      'Endurance',
      'Intimidate',
      'Lore (Albion)',
      'Lore (Beasts)',
      'Lore (Monsters)',
      'Melee (Basic)',
      'Melee (Polearm)',
      'Outdoor Survival',
      'Ranged (Throwing)',
      'Stealth (Rural)',
    ],
    'arabyan-nom': [
      'Art (Any)',
      'Evaluate',
      'Gossip',
      'Haggle',
      'Language (Indan)',
      'Language (Southlander)',
      'Language (Wastelander)',
      'Lore (Local)',
      'Melee (Basic)',
      'Navigation',
      'Pray',
      'Ride (Camel)',
      'Ride (Horse)',
      'Sail (any one)',
    ],
    'breton-noble-nom': [
      'Charm Animal',
      'Charm',
      'Cool',
      'Gossip',
      'Haggle',
      'Language (Any)',
      'Leadership',
      'Lore (Local)',
      'Lore (Politics)',
      'Melee (Basic)',
      'Melee (Two-Handed)',
      'Pray',
      'Ride (Horse)',
    ],
    'breton-lowborn-nom': [
      'Animal Care',
      'Charm Animal',
      'Cool',
      'Endurance',
      'Gossip',
      'Haggle',
      'Lore (Local)',
      'Lore (Agriculture)',
      'Melee (Basic)',
      'Ranged (Bow)',
      'Ride (Horse)',
      'Trade (Farmer)',
    ],
    'cathayan-nom': [
      'Art (Any)',
      'Charm',
      'Climb',
      'Gossip',
      'Haggle',
      'Language (Indan)',
      'Language (Nipponese)',
      'Language (Wastelander)',
      'Leadership',
      'Lore (Local)',
      'Melee (Basic)',
      'Ranged (Bow)',
    ],
    'estalian-nom': [
      'Athletics',
      'Bribery',
      'Charm',
      'Consume Alcohol',
      'Entertain (Storytelling)',
      'Gossip',
      'Language (Bretonnian)',
      'Language (Tilean)',
      'Language (Arabyan)',
      'Lore (Local)',
      'Perform (Jota)',
      'Sleight of Hand',
    ],
    'indan-nom': [
      'Animal Care',
      'Charm',
      'Cool',
      'Endurance',
      'Gossip',
      'Haggle',
      'Language (Arabyan)',
      'Language (Cathayan)',
      'Language (Wastelander)',
      'Lore (Local)',
      'Melee (Basic)',
      'Ranged (Throwing)',
    ],
    'gospodar-nom': [
      'Animal Care',
      'Charm Animal',
      'Cool',
      'Evaluate',
      'Gossip',
      'Haggle',
      'Language (Wastelander)',
      'Language (Norse)',
      'Language (Ungol)',
      'Lore (Kislev)',
      'Melee (Basic)',
      'Ranged (Bow)',
      'Ride (Horse)',
    ],
    'ungol-nom': [
      'Animal Care',
      'Charm Animal',
      'Cool',
      'Drive',
      'Gossip',
      'Haggle',
      'Intimidate',
      'Language (Gospodarinyi)',
      'Lore (Kislev)',
      'Melee (Basic)',
      'Outdoor Survival',
      'Ranged (Bow)',
    ],
    'nipponese-nom': [
      'Charm',
      'Cool',
      'Gossip',
      'Haggle',
      'Language (Cathayan)',
      'Language (Wastelander)',
      'Leadership',
      'Lore (Nippon)',
      'Melee (Basic)',
      'Ranged (Bow)',
      'Sail (any one)',
      'Swim',
    ],
    'norscan-nom': [
      'Athletics',
      'Climb',
      'Consume Alcohol',
      'Cool',
      'Endurance',
      'Intimidate',
      'Lore (Norsca)',
      'Melee (Basic)',
      'Melee (Two-Handed)',
      'Outdoor Survival',
      'Perception',
      'Sail (any one)',
      'Swim',
    ],
    'southlander-nom': [
      'Animal Care',
      'Athletics',
      'Climb',
      'Cool',
      'Endurance',
      'Gossip',
      'Language (Arabyan)',
      'Language (Cathayan)',
      'Melee (Polearm)',
      'Navigation',
      'Outdoor Survival',
      'Perception',
      'Ranged (Throwing)',
    ],
    'strigany-nom': [
      'Animal Care',
      'Charm Animal',
      'Charm',
      'Entertain (Sing)',
      'Entertain (Storytelling)',
      'Gossip',
      'Haggle',
      'Language (Any)',
      'Lore (Local)',
      'Lore (Spirits)',
      'Perform (Any)',
      'Play (Any)',
      'Ride (Horse)',
    ],
    'tilean-nom': [
      'Art (Any)',
      'Bribery',
      'Charm',
      'Consume Alcohol',
      'Entertain (Storytelling)',
      'Gossip',
      'Language (Estalian)',
      'Language (Bretonnian)',
      'Lore (Politics)',
      'Lore (Local)',
      'Sail (any one)',
      'Sleight of Hand',
    ],
    'westerlander-nom': [
      'Bribery',
      'Charm',
      'Cool',
      'Evaluate',
      'Gossip',
      'Haggle',
      'Language (Arabyan)',
      'Language (Bretonnian)',
      'Language (Cathayan)',
      'Language (Nipponese)',
      'Language (Estalian)',
      'Language (Tilean)',
      'Lore (Westerland)',
      'Sail (any one)',
      'Trade (Any)',
    ],
    reiklander: [
      'Animal Care',
      'Charm',
      'Cool',
      'Evaluate',
      'Gossip',
      'Haggle',
      'Language (Bretonnian)',
      'Language (Wastelander)',
      'Leadership',
      'Lore (Reikland)',
      'Melee (Basic)',
      'Ranged (Bow)',
    ],
    middenheimer: [
      'Bribery',
      'Charm',
      'Cool',
      'Entertain (Any)',
      'Evaluate',
      'Gossip',
      'Haggle',
      'Leadership',
      'Lore (Middenheim)',
      'Melee (Basic)',
      'Ranged (Bow)',
      'Trade (any one)',
    ],
    middenlander: [
      'Animal Care',
      'Cool',
      'Evaluate',
      'Gossip',
      'Haggle',
      'Intimidate',
      'Language (Wastelander)',
      'Leadership',
      'Lore (Middenland)',
      'Melee (Basic)',
      'Outdoor Survival',
      'Ranged (Bow)',
    ],
    nordlander: [
      'Consume Alcohol',
      'Evaluate',
      'Gossip',
      'Haggle',
      'Language (Norse)',
      'Language (Wastelander)',
      'Lore (Nordland)',
      'Melee (Basic)',
      'Ranged (Bow)',
      'Sail (any one)',
      'Swim',
      'Trade (any one)',
    ],
  },
  dwarf: {
    greydwarf: [
      'Consume Alcohol',
      'Cool',
      'Endurance',
      'Entertain (Storytelling)',
      'Evaluate',
      'Intimidate',
      'Language (Khazalid)',
      'Lore (Dwarfs)',
      'Lore (Geology)',
      'Lore (Metallurgy)',
      'Melee (Basic)',
      'Trade (Any)',
    ],
    norsedwarf: [
      'Consume Alcohol',
      'Cool',
      'Endurance',
      'Intimidate',
      'Language (Khazalid) ',
      'Language (Norse)',
      'Lore (Chaos)',
      'Lore (Dwarfs)',
      'Lore (Norsca)',
      'Melee (Basic)',
      'Melee (Two-Handed)',
      'Trade (Any)',
    ],
    imperialdwarf: [
      'Charm',
      'Consume Alcohol',
      'Cool',
      'Entertain (Storytelling)',
      'Evaluate',
      'Haggle',
      'Language (Bretonnian)',
      'Language (Estalian)',
      'Language (Tilean)',
      'Language (Khazalid)',
      'Lore (Dwarfs)',
      'Lore (Empire)',
      'Lore (Local)',
      'Melee (Basic)',
      'Trade (Any)',
    ],
  },
  halfling: {
    ashfield: [
      'Charm',
      'Consume Alcohol',
      'Haggle',
      'Lore (Reikland)',
      'Sleight of Hand',
      'Stealth (Any)',
      'Trade (Cook)',
      'Cool',
      'Intuition',
      'Language (Mootish)',
      'Ranged (any)',
    ],
    brambledown: [
      'Charm',
      'Consume Alcohol',
      'Haggle',
      'Lore (Reikland)',
      'Sleight of Hand',
      'Stealth (Any)',
      'Trade (Cook)',
      'Language (Mootish) ',
      'Navigation',
      'Outdoor Survival ',
      'Swim',
    ],
    brandysnap: [
      'Charm',
      'Consume Alcohol',
      'Haggle',
      'Lore (Reikland)',
      'Sleight of Hand',
      'Stealth (Any)',
      'Trade (Cook)',
      'Animal Care',
      'Gamble',
      'Language (Mootish)',
      'Lore (Herbs)',
    ],
    hayfoot: [
      'Charm',
      'Consume Alcohol',
      'Haggle',
      'Lore (Reikland)',
      'Sleight of Hand',
      'Stealth (Any)',
      'Trade (Cook)',
      'Gamble',
      'Haggle',
      'Evaluate',
      'Language (Mootish)',
    ],
    hollyfoot: [
      'Charm',
      'Consume Alcohol',
      'Haggle',
      'Lore (Reikland)',
      'Sleight of Hand',
      'Stealth (Any)',
      'Trade (Cook)',
      'Bribery',
      'Haggle',
      'Gossip',
      'Language (Mootish)',
    ],
    'hayfoot—hollyfoot': [
      'Charm',
      'Consume Alcohol',
      'Haggle',
      'Lore (Reikland)',
      'Sleight of Hand',
      'Stealth (Any)',
      'Trade (Cook)',
      'Bribery',
      'Haggle',
      'Gossip',
      'Language (Mootish)',
    ],
    'hayfoot-hollyfoot': [
      'Charm',
      'Consume Alcohol',
      'Haggle',
      'Lore (Reikland)',
      'Sleight of Hand',
      'Stealth (Any)',
      'Trade (Cook)',
      'Bribery',
      'Haggle',
      'Gossip',
      'Language (Mootish)',
    ],
    lostpockets: [
      'Charm',
      'Consume Alcohol',
      'Haggle',
      'Lore (Reikland)',
      'Sleight of Hand',
      'Stealth (Any)',
      'Trade (Cook)',
      'Endurance',
      'Gamble',
      'Gossip',
      'Intuition',
    ],
    lowhaven: [
      'Charm',
      'Consume Alcohol',
      'Haggle',
      'Lore (Reikland)',
      'Sleight of Hand',
      'Stealth (Any)',
      'Trade (Cook)',
      'Bribery',
      'Haggle',
      'Intimidate',
      'Language (Mootish)',
    ],
    rumster: [
      'Charm',
      'Consume Alcohol',
      'Haggle',
      'Lore (Reikland)',
      'Sleight of Hand',
      'Stealth (Any)',
      'Trade (Cook)',
      'Endurance',
      'Gossip',
      'Haggle',
      'Language (Mootish)',
    ],
    skelfsider: [
      'Charm',
      'Consume Alcohol',
      'Haggle',
      'Lore (Reikland)',
      'Sleight of Hand',
      'Stealth (Any)',
      'Trade (Cook)',
      'Endurance',
      'Gamble',
      'Gossip',
      'Language (Mootish)',
    ],
    thorncobble: [
      'Charm',
      'Consume Alcohol',
      'Haggle',
      'Lore (Reikland)',
      'Sleight of Hand',
      'Stealth (Any)',
      'Trade (Cook)',
      'Gossip',
      'Leadership',
      'Lore (Heraldry)',
      'Language (Mootish)',
    ],
    tumbleberry: [
      'Charm',
      'Consume Alcohol',
      'Haggle',
      'Lore (Reikland)',
      'Sleight of Hand',
      'Stealth (Any)',
      'Trade (Cook)',
      'Gossip',
      'Haggle',
      'Lore (Any)',
      'Language (Mootish)',
    ],
  },
};

export const subSpeciesOthers = {
  human: {
    'averlander-nom': [
      `Doomed, ${psychologyPrefix}Hatred (Greenskins)`,
      `Etiquette (Dwarfs), ${randomTalent}1`,
      'Sharp, Suave',
      2,
    ],
    'hochlander-nom': ['Doomed, Rover', 'Marksman, Sharp', 3],
    'ostermarker-nom': [`Doomed, ${randomTalent}1`, 'Marksman, Coolheaded', 3],
    'ostlander-nom': [
      `Doomed, ${randomTalent}1`,
      'Very Resilient, Stone Soup',
      3,
    ],
    'stirlander-nom': [`Doomed, ${randomTalent}1`, 'Nimble Fingered, Suave', 3],
    'sylvanian-nom': ['Coolheaded, Sharp', 'Flee!', 3],
    'talabeclander-nom': ['Doomed, Accurate Shot', 'Marksman, Savvy', 3],
    'wissenlander-nom': ['Doomed', 'Coolheaded, Savvy', 3],
    'albionite-nom': [
      'Resistance (Mutation)',
      'Stone Soup',
      'Strider (Marshes)',
      'Warrior Born',
      'Very Strong, Very Resilient',
      0,
    ],
    'arabyan-nom': [
      'Nimble Fingered, Suave',
      'Read/Write, Craftsman (Any)',
      'Resistance (Heat), Strider (Deserts)',
      origin,
      0,
    ],
    'breton-noble-nom': [
      'Noble Blood',
      'Read/Write',
      'Suave, Warrior Born',
      origin,
      0,
    ],
    'breton-lowborn-nom': [
      'Nimble Fingered, Very Resilient',
      'Stone Soup',
      'Strong Back',
      origin,
      0,
    ],
    'cathayan-nom': ['Coolheaded, Savvy', 'Read/Write, Linguistics', origin, 0],
    'estalian-nom': ['Nose for Trouble', 'Savvy, Suave', origin, 0],
    'indan-nom': [
      'Lightning Reflexes, Suave',
      'Luck',
      `Resistance (Heat), ${randomTalent}1`,
      origin,
      0,
    ],
    'gospodar-nom': [
      'Resistance (Cold)',
      'Suave, Savvy',
      'Very Strong, Warrior Born',
      origin,
      0,
    ],
    'ungol-nom': [
      `Hardy, ${randomTalent}1`,
      'Resistance (Cold)',
      'Marksman, Very Resilient',
      origin,
      0,
    ],
    'nipponese-nom': ['Sixth Sense', 'Warrior Born, Sharp', origin, 0],
    'norscan-nom': [
      'Night Vision',
      'Resistance (Cold)',
      'Very Strong, Warrior Born',
      `${origin}, ${randomTalent}2`,
      0,
    ],

    'southlander-nom': [
      'Lightning Reflexes, Sprinter',
      `Strong Legs, ${randomTalent}1`,
      origin,
      0,
    ],

    'strigany-nom': [
      'Animal Affinity, Perfect Pitch',
      'Seasoned Traveller',
      'Sharp, Suave',
      2,
    ],
    'tilean-nom': [
      `Gregarious, ${randomTalent}1`,
      `Read/Write, ${randomTalent}1`,
      'Sharp, Suave',
      origin,
      0,
    ],
    'westerlander-nom': ['Briber, Dealmaker', 'Savvy, Suave', 3],
    reiklander: ['Doomed', 'Savvy, Suave', 3],
    middenheimer: ['Doomed', 'Etiquette (any one), Strong Back', 3],
    middenlander: [`Doomed, ${randomTalent}1`, 'Menacing, Warrior Born', 3],
    nordlander: [
      `Doomed, ${randomTalent}1`,
      'Fisherman, Rover',
      'Stout-hearted, Very Resilient',
      2,
    ],
  },
  dwarf: {
    greydwarf: [
      'Craftsman (Any), Linguistics',
      'Night Vision',
      'Magic Resistance',
      'Nimble Fingered, Read/Write',
      'Sixth Sense, Sturdy',
      0,
    ],
    norsedwarf: [
      'Magic Resistance',
      'Night Vision',
      'Pure Soul, Read/Write',
      'Resistance (Mutation), Robust',
      'Stout-hearted, Sturdy',
      0,
    ],
    imperialdwarf: [
      'Magic Resistance',
      'Night Vision',
      'Read/Write, Sturdy',
      2,
    ],
  },
  welf: {
    harioth: [
      'Acute Sense (WFRP4NPCGEN.sight)',
      'Hardy, Second Sight',
      'Night Vision',
      'Read/Write, Very Resilient',
      'Rover',
      'Youngblood',
      0,
    ],
  },
  halfling: {
    ashfield: [
      'Acute Sense (WFRP4NPCGEN.taste)',
      'Night Vision',
      'Resistance (Chaos)',
      'Small',
      'Acute Sense (WFRP4NPCGEN.sight), Etiquette (Soldiers)',
      1,
    ],
    brambledown: [
      'Acute Sense (WFRP4NPCGEN.taste)',
      'Night Vision',
      'Resistance (Chaos)',
      'Small',
      'Gregarious, Seasoned Traveller',
      1,
    ],
    brandysnap: [
      'Acute Sense (WFRP4NPCGEN.taste)',
      'Night Vision',
      'Resistance (Chaos)',
      'Small',
      'Craftsman (Farmer), Sturdy',
      1,
    ],
    hayfoot: [
      'Acute Sense (WFRP4NPCGEN.taste)',
      'Night Vision',
      'Resistance (Chaos)',
      'Small',
      'Dealmaker, Etiquette (Guilders)',
      1,
    ],
    hollyfoot: [
      'Acute Sense (WFRP4NPCGEN.taste)',
      'Night Vision',
      'Resistance (Chaos)',
      'Small',
      'Craftsman (Any), Nimble Fingered',
      1,
    ],
    'hayfoot—hollyfoot': [
      'Acute Sense (WFRP4NPCGEN.taste)',
      'Night Vision',
      'Resistance (Chaos)',
      'Small',
      'Argumentative, Numismatics',
      1,
    ],
    'hayfoot-hollyfoot': [
      'Acute Sense (WFRP4NPCGEN.taste)',
      'Night Vision',
      'Resistance (Chaos)',
      'Small',
      'Argumentative, Numismatics',
      1,
    ],
    lostpockets: [
      'Acute Sense (WFRP4NPCGEN.taste)',
      'Night Vision',
      'Resistance (Chaos)',
      'Small',
      'Hardy, Stone Soup',
      1,
    ],
    lowhaven: [
      'Acute Sense (WFRP4NPCGEN.taste)',
      'Night Vision',
      'Resistance (Chaos)',
      'Small',
      'Criminal, Etiquette (Criminals), Etiquette (Guilders)',
      1,
    ],
    rumster: [
      'Acute Sense (WFRP4NPCGEN.taste)',
      'Night Vision',
      'Resistance (Chaos)',
      'Small',
      'Craftsman (Cook), Dealmaker',
      1,
    ],
    skelfsider: [
      'Acute Sense (WFRP4NPCGEN.taste)',
      'Night Vision',
      'Resistance (Chaos)',
      'Small',
      'Beneath Notice, Etiquette (Servants)',
      1,
    ],
    thorncobble: [
      'Acute Sense (WFRP4NPCGEN.taste)',
      'Night Vision',
      'Resistance (Chaos)',
      'Small',
      'Etiquette (Nobles), Etiquette (Scholar), Read/Write',
      1,
    ],
    tumbleberry: [
      'Acute Sense (WFRP4NPCGEN.taste)',
      'Night Vision',
      'Resistance (Chaos)',
      'Small',
      'Etiquette (Burgher), Etiquette (Guilders), Read/Write',
      1,
    ],
  },
};

const bretonOrigin = {
  languille: ['Dealmaker, Old Salt', 1],
  aquitaine: ['Coolheaded', 1],
  artois: [
    `${psychologyPrefix}Hatred (Beastmen)`,
    'Very Resilient, Very Strong',
    0,
  ],
  bastonne: ['Stout-hearted', 1],
  bordeleaux: ['Carouser, Sea Legs', 1],
  brionne: ['Artistic, Perfect Pitch', 1],
  carcassonne: ['Warrior Born', 1],
  couronne: ['Craftsman (Farrier), Trick Riding', 1],
  gisoreux: ['Seasoned Traveller, Strider (Mountains)', 1],
  lyonesse: ['Cat-tongued, Schemer', 1],
  montfort: ['Hardy', 1],
  mousillon: ['Strong-minded', 1],
  parravon: ['Animal Affinity, Sixth Sense', 1],
  quenelles: [`${psychologyPrefix}Hatred (Greenskins)`, 1],
};

const kislevOrigin = {
  northernkislev: ['Night Vision', 1],
  easternkislev: ['Strong-minded', 1],
  westernkislev: ['Old Salt, Sea Legs', 1],
  southernkislev: [2],
};

export const originNames = {
  copher: 'Copher',
  elkalabad: 'El-Kalabad',
  lashiek: 'Lashiek',
  martek: 'Martek',
  sudenberg: 'Sudenberg',
  antoch: 'Antoch',
  sartosa: 'Sartosa',
  nomad: 'Nomad',
  languille: "L'Anguille",
  aquitaine: 'Aquitaine',
  artois: 'Artois',
  bastonne: 'Bastonne',
  bordeleaux: 'Bordeleaux',
  brionne: 'Brionne',
  carcassonne: 'Carcassonne',
  couronne: 'Couronne',
  gisoreux: 'Gisoreux',
  lyonesse: 'Lyonesse',
  montfort: 'Montfort',
  mousillon: 'Mousillon',
  parravon: 'Parravon',
  quenelles: 'Quenelles',
  weijin: 'Weijin',
  nangau: 'Nan-Gau',
  fuchow: 'Fu-Chow',
  shangyang: 'Shang-Yang',
  xianbei: 'Xianbei',
  yuanjin: 'Yuanjin',
  hankuo: 'Han Kuo',
  aradon: 'Aradón',
  catilinia: 'Catilinia',
  vanlen: 'Vanlen',
  navarr: 'Navarr',
  castill: 'Castill',
  laon: 'Laon',
  gaellica: 'Gaellica',
  vasconia: 'Vasconia',
  andal: 'Andal',
  murc: 'Murc',
  portul: 'Portul',
  kingdomofbhalluka: 'WFRP4NPCGEN.bhalluka',
  kingdomofgandharva: 'WFRP4NPCGEN.gandharva',
  kingdomofsingha: 'WFRP4NPCGEN.singha',
  kingdomoflakshana: 'WFRP4NPCGEN.lakshana',
  kingdomofpanchala: 'WFRP4NPCGEN.panchala',
  kingdomofkosala: 'WFRP4NPCGEN.kosala',
  kingdomofkurya: 'WFRP4NPCGEN.kurya',
  northernkislev: 'WFRP4NPCGEN.northernkislev',
  easternkislev: 'WFRP4NPCGEN.easternkislev',
  westernkislev: 'WFRP4NPCGEN.westernkislev',
  southernkislev: 'WFRP4NPCGEN.southernkislev',
  northernclans: 'WFRP4NPCGEN.northernclans',
  easternclans: 'WFRP4NPCGEN.easternclans',
  westernclans: 'WFRP4NPCGEN.westernclans',
  southernclans: 'WFRP4NPCGEN.southernclans',
  aeslingstribe: 'WFRP4NPCGEN.aeslingstribe',
  baersonlingstribe: 'WFRP4NPCGEN.baersonlingstribe',
  bjornlingstribe: 'WFRP4NPCGEN.bjornlingstribe',
  graelingstribe: 'WFRP4NPCGEN.graelingstribe',
  sarlstribe: 'WFRP4NPCGEN.sarlstribe',
  skaelingstribe: 'WFRP4NPCGEN.skaelingstribe',
  skeggitribe: 'WFRP4NPCGEN.skeggitribe',
  vargstribe: 'WFRP4NPCGEN.vargstribe',
  northernsouthlandstribes: 'WFRP4NPCGEN.northernsouthlandstribes',
  easternsouthlandstribes: 'WFRP4NPCGEN.easternsouthlandstribes',
  westernsouthlandstribes: 'WFRP4NPCGEN.westernsouthlandstribes',
  southernsouthlandstribes: 'WFRP4NPCGEN.southernsouthlandstribes',
  remas: 'Remas',
  luccini: 'Luccini',
  trantio: 'Trantio',
  pavona: 'Pavona',
  verezzo: 'Verezzo',
  miragliano: 'Miragliano',
  tobaro: 'Tobaro',
  newworldcolonies: 'WFRP4NPCGEN.newworldcolonies',
  goldtoothtribe: 'WFRP4NPCGEN.goldtoothtribe',
  thundergutstribe: 'WFRP4NPCGEN.thundergutstribe',
  crossedclubs: 'WFRP4NPCGEN.crossedclubs',
  thesonsofthemountain: 'WFRP4NPCGEN.thesonsofthemountain',
  feastmastertribe: 'WFRP4NPCGEN.feastmastertribe',
  rockskulls: 'WFRP4NPCGEN.rockskulls',
  bloodguzzlers: 'WFRP4NPCGEN.bloodguzzlers',
  ironskintribe: 'WFRP4NPCGEN.ironskintribe',
  thelazarghs: 'WFRP4NPCGEN.thelazarghs',
  mountaineaterstribe: 'WFRP4NPCGEN.mountaineaterstribe',
  eyebitertribe: 'WFRP4NPCGEN.eyebitertribe',
};

export const speciesOrigin = {
  ogre: {
    goldtoothtribe: ['Wealthy', 0],
    thundergutstribe: ['Menacing', 0],
    crossedclubs: ['Warrior Born', 0],
    thesonsofthemountain: ["Hunter's Eye", 0],
    feastmastertribe: ['Etiquette (Halflings)', 0],
    rockskulls: ['Strong Back', 0],
    bloodguzzlers: ['Resistance (Poison)', 0],
    ironskintribe: ['Berserk Charge', 0],
    thelazarghs: ['Tenacious', 0],
    mountaineaterstribe: ['Iron Gut', 0],
    eyebitertribe: ['Sprinter', 0],
  },
};

export const subSpeciesOrigins = {
  human: {
    'arabyan-nom': {
      copher: ['Briber, Dealmaker', 1],
      elkalabad: ['Alley Cat, Fast Hands', 1],
      lashiek: ['Sea Legs, Sturdy', 1],
      martek: ['Craftsman (Mining), Tunnel Rat', 1],
      sudenberg: ['Linguistics, Numismatics', 1],
      antoch: [
        'Marksman, Warrior Born',
        `${psychologyPrefix}Prejudice (Bretonnians)`,
        0,
      ],
      sartosa: ['Criminal', 1],
      nomad: ['Stone Soup', 1],
    },
    'breton-noble-nom': bretonOrigin,
    'breton-lowborn-nom': bretonOrigin,
    'cathayan-nom': {
      weijin: [3],
      nangau: ['Craftsman (Engineering), Warrior Born', 2],
      fuchow: ['Fisherman', 'Sea Legs', 1],
      shangyang: ['Suave', 2],
      xianbei: [`${psychologyPrefix}Hatred (Skavens)`, 'Warrior Born', 1],
      yuanjin: ['Coolheaded', 2],
      hankuo: ['Very Resilient, Very Strong', 2],
    },
    'estalian-nom': {
      aradon: ['Coolheaded', 2],
      catilinia: ['Cat-tongued', 2],
      vanlen: ['Gregarious', 2],
      navarr: ['Mimic', 2],
      castill: ['Stout-hearted', 2],
      laon: ['Hardy', 2],
      gaellica: ['Field Dressing', 2],
      vasconia: ['Lightning Reflexes', 'Menacing', 1],
      andal: ['Craftsman (Trade)', 'Read/Write', 1],
      murc: ['Beneath Notice', 2],
      portul: ['Sharp', 'Read/Write', 1],
      sartosa: ['Criminal', 2],
    },
    'indan-nom': {
      kingdomofbhalluka: [`${psychologyPrefix}Hatred (Daemons)`, 1],
      kingdomofgandharva: ['Pure Soul', 1],
      kingdomofsingha: ['Roughrider, Seasoned Traveller', 1],
      kingdomoflakshana: ['Artistic, Nimble Fingered', 1],
      kingdomofpanchala: [2],
      kingdomofkosala: ['Dealmaker', 1],
      kingdomofkurya: ['Warrior Born', 1],
    },
    'gospodar-nom': kislevOrigin,
    'ungol-nom': kislevOrigin,
    'nipponese-nom': {
      northernclans: ['Suave', 2],
      easternclans: ['Lightning Reflexes', 2],
      westernclans: ['Savvy', 2],
      southernclans: ['Very Resilient', 2],
    },
    'norscan-nom': {
      aeslingstribe: ['Menacing', 'Warrior Born', 0],
      baersonlingstribe: ['Sturdy', 'Very Resilient', 0],
      bjornlingstribe: ['Strong Back', 'Very Strong', 0],
      graelingstribe: ['Relentless', 'Warrior Born', 0],
      sarlstribe: ['Lightning Reflexes', 'Strider (Snow)', 0],
      skaelingstribe: ['Sharp', 'Sixth Sense', 0],
      skeggitribe: ['Coolheaded', 'Resistance (Disease)', 0],
      vargstribe: ['Resolute', 'Warrior Born', 0],
    },
    'southlander-nom': {
      northernsouthlandstribes: ['Etiquette (Lizardmen),  Suave', 2],
      easternsouthlandstribes: ['Ambidextrous, Warrior Born', 2],
      westernsouthlandstribes: [`Flee!, ${psychologyPrefix}Hatred (Undead)`, 2],
      southernsouthlandstribes: [3],
    },
    'tilean-nom': {
      remas: ['Etiquette (Merchants)', 1],
      luccini: ['Etiquette (Mymidians)', 1],
      trantio: ['Etiquette (Artists)', 1],
      pavona: ['Etiquette (Carpenters)', 1],
      verezzo: ['Etiquette (Politics)', 1],
      sartosa: ['Etiquette (Pirates)', 1],
      miragliano: ['Etiquette (Rat Catchers)', 1],
      tobaro: ['Etiquette (Miner)', 1],
      newworldcolonies: ['Etiquette (Adventurers)', 1],
    },
  },
};

export const randomTalents = [
  'Acute Sense (any one)',
  'Ambidextrous',
  'Animal Affinity',
  'Artistic',
  'Attractive',
  'Coolheaded',
  'Craftsman (any one)',
  'Flee!',
  'Hardy',
  'Lightning Reflexes',
  'Linguistics',
  'Luck',
  'Marksman',
  'Mimic',
  'Night Vision',
  'Nimble Fingered',
  'Noble Blood',
  'Orientation',
  'Perfect Pitch',
  'Pure Soul',
  'Read/Write',
  'Resistance (any one)',
  'Savvy',
  'Sharp',
  'Sixth Sense',
  'Strong Legs',
  'Sturdy',
  'Suave',
  'Super Numerate',
  'Very Resilient',
  'Very Strong',
  'Warrior Born',
];
