export const speciesSkills = {
  ogre: [
    'Consume Alcohol',
    'Cool',
    'Endurance',
    'Gamble',
    'Intimidate',
    'Language (Any)',
    'Language (Grumbarth)',
    'Language (Mootish)',
    'Lore (Ogres)',
    'Melee (Basic)',
    'Melee (Brawling)',
    'Trade (Cook)',
  ],
  human: [
    'Animal Care',
    'Charm',
    'Cool',
    'Evaluate',
    'Gossip',
    'Haggle',
    'Language (Bretonnian)',
    'Language (Wastelander)',
    'Leadership',
    'Lore (Reikland)',
    'Melee (Basic)',
    'Ranged (Bow)',
  ],
  dwarf: [
    'Consume Alcohol',
    'Cool',
    'Endurance',
    'Entertain (Storytelling)',
    'Evaluate',
    'Intimidate',
    'Language (Khazalid)',
    'Lore (Dwarfs)',
    'Lore (Geology)',
    'Lore (Metallurgy)',
    'Melee (Basic)',
    'Trade (any one)',
  ],
  halfling: [
    'Charm',
    'Consume Alcohol',
    'Dodge',
    'Gamble',
    'Haggle',
    'Intuition',
    'Language (Mootish)',
    'Lore (Reikland)',
    'Perception',
    'Sleight of Hand',
    'Stealth (Any)',
    'Trade (Cook)',
  ],
  helf: [
    'Cool',
    'Entertain (Sing)',
    'Evaluate',
    'Language (Eltharin)',
    'Leadership',
    'Melee (Basic)',
    'Navigation',
    'Perception',
    'Play (any one)',
    'Ranged (Bow)',
    'Sail(any one)',
    'Swim',
  ],
  welf: [
    'Athletics',
    'Climb',
    'Endurance',
    'Entertain (Sing)',
    'Intimidate',
    'Language (Eltharin)',
    'Melee (Basic)',
    'Outdoor Survival',
    'Perception',
    'Ranged (Bow)',
    'Stealth (Rural)',
    'Track',
  ],
  gnome: [
    'Channelling (Ulgu)',
    'Charm',
    'Consume Alcohol',
    'Dodge',
    'Entertain (Any)',
    'Gossip',
    'Haggle',
    'Language (Ghassally)',
    'Language (Magick)',
    'Language (Wastelander)',
    'Outdoor Survival',
    'Stealth (Any)',
  ],
};

export const speciesTalents = {
  ogre: [
    'Acute Sense (WFRP4NPCGEN.smell), Acute Sense (WFRP4NPCGEN.taste)',
    'Resistance (Mutation), Strong-minded',
    'Night Vision',
    'Very Resilient, Very Strong',
    0,
  ],
  human: ['Doomed', 'Savvy, Suave', 3],
  dwarf: [
    'Magic Resistance',
    'Night Vision',
    'Read/Write, Relentless',
    'Resolute, Strong-minded',
    'Sturdy',
    0,
  ],
  halfling: [
    'Acute Sense (WFRP4NPCGEN.taste)',
    'Night Vision',
    'Resistance (Chaos)',
    'Small',
    2,
  ],
  helf: [
    'Acute Sense (WFRP4NPCGEN.sight)',
    'Coolheaded, Savvy',
    'Night Vision',
    'Second Sight, Sixth Sense',
    'Read/Write',
    0,
  ],
  welf: [
    'Acute Sense (WFRP4NPCGEN.sight)',
    'Hardy, Second Sight',
    'Night Vision',
    'Read/Write, Very Resilient',
    'Rover',
    0,
  ],
  gnome: [
    'Beneath Notice, Suffused with Ulgu',
    'Luck, Mimic',
    'Night Vision',
    'Fisherman, Read/Write',
    'Second Sight, Sixth Sense',
    'Small',
    0,
  ],
};

export const speciesTraits = {
  ogre: ['Bite', 'Size (Large)'],
};

export const speciesPsychologies = {
  ogre: ['Ogre Hunger', 'Favorite Snack (any one)'],
};

export const subSpeciesSkills = {
  human: {
    'averlander-nom': {
      skills: [
        'Animal Care',
        'Charm Animal',
        'Entertain (Speeches)',
        'Gossip',
        'Language (Bretonnian)',
        'Language (Khazalid)',
        'Language (Mootish)',
        'Leadership',
        'Lore (Averland)',
        'Melee (Basic)',
        'Ride (Horse)',
        'Trade (Farmer)',
      ],
    },
    'hochlander-nom': {
      skills: [
        'Animal Care',
        'Charm',
        'Cool',
        'Haggle,',
        'Lore (Hochland)',
        'Melee (Basic)',
        'Outdoor Survival',
        'Perception',
        'Ranged (Bow)',
        'Ranged (Blackpowder)',
        'Secret Signs (Hunters)',
        'Stealth (Rural)',
        'Track',
      ],
    },
    'ostermarker-nom': {
      skills: [
        'Consume Alcohol',
        'Cool',
        'Endurance',
        'Haggle',
        'Intimidate',
        'Intuition',
        'Language (Gospodarinyi)',
        'Language (Ungol)',
        'Leadership',
        'Lore (Ostermark)',
        'Melee (Basic)',
        'Melee (Polearm)',
        'Ranged (Bow)',
      ],
    },
    'ostlander-nom': {
      skills: [
        'Cool',
        'Endurance',
        'Gamble',
        'Intimidate',
        'Language (Gospodarinyi)',
        'Language (Ungol)',
        'Lore (Ostland)',
        'Melee (Basic)',
        'Navigation',
        'Outdoor Survival',
        'Sail',
        'Swim',
      ],
    },
    'stirlander-nom': {
      skills: [
        'Bribery',
        'Cool',
        'Evaluate',
        'Gossip',
        'Haggle',
        'Language (Mootish)',
        'Leadership',
        'Lore (Stirland)',
        'Melee (Basic)',
        'Ranged (Bow)',
        'Sleight of Hand',
        'Stealth (Rural)',
        'Stealth (Urban)',
      ],
    },
    'sylvanian-nom': {
      skills: [
        'Animal Care',
        'Athletics',
        'Charm Animal',
        'Charm',
        'Cool',
        'Endurance',
        'Lore (Sylvania)',
        'Lore (Undead)',
        'Lore (Vampires)',
        'Melee (Basic)',
        'Melee (Polearm)',
        'Outdoor Survival',
        'Stealth (Rural)',
      ],
    },
    'talabeclander-nom': {
      skills: [
        'Animal Care',
        'Charm Animal',
        'Cool',
        'Gossip',
        'Haggle',
        'Lore (Talabecland)',
        'Melee (Basic)',
        'Navigation',
        'Outdoor Survival',
        'Perception',
        'Ranged (Bow)',
        'Track',
      ],
    },
    'wissenlander-nom': {
      skills: [
        'Animal Care',
        'Cool',
        'Endurance',
        'Haggle',
        'Intuition',
        'Language (Bretonnian)',
        'Language (Estalian)',
        'Language (Tilean)',
        'Leadership',
        'Lore (Wissenland)',
        'Melee (Basic)',
        'Ranged (Blackpowder)',
        'Trade (Farmer)',
        'Trade (Miner)',
      ],
    },
    'albionite-nom': {
      skills: [
        'Athletics',
        'Climb',
        'Cool',
        'Endurance',
        'Intimidate',
        'Lore (Albion)',
        'Lore (Beasts)',
        'Lore (Monsters)',
        'Melee (Basic)',
        'Melee (Polearm)',
        'Outdoor Survival',
        'Ranged (Throwing)',
        'Stealth (Rural)',
      ],
    },
    'arabyan-nom': {
      name: 'Arabyan',
      skills: [
        'Art (Any)',
        'Evaluate',
        'Gossip',
        'Haggle',
        'Language (Indan)',
        'Language (Southlander)',
        'Language (Wastelander)',
        'Lore (City State)',
        'Melee (Basic)',
        'Navigation',
        'Pray',
        'Ride (Camel)',
        'Ride (Horse)',
        'Sail',
      ],
    },
    'breton-noble-nom': {
      skills: [
        'Charm Animal',
        'Charm',
        'Cool',
        'Gossip',
        'Haggle',
        'Language (Any)',
        'Leadership',
        'Lore (Dukedom)',
        'Lore (Politics)',
        'Melee (Basic)',
        'Melee (Two-Handed)',
        'Pray',
        'Ride (Horse)',
      ],
    },
    'breton-lowborn-nom': {
      skills: [
        'Animal Care',
        'Charm Animal',
        'Cool',
        'Endurance',
        'Gossip',
        'Haggle',
        'Lore (Dukedom)',
        'Lore (Agriculture)',
        'Melee (Basic)',
        'Ranged (Bow)',
        'Ride (Horse)',
        'Trade (Farmer)',
      ],
    },
    'cathayan-nom': {
      name: 'Cathayan',
      skills: [
        'Art (Any)',
        'Charm',
        'Climb',
        'Gossip',
        'Haggle',
        'Language (Indan)',
        'Language (Nipponese)',
        'Language (Wastelander)',
        'Leadership',
        'Lore (Province)',
        'Melee (Basic)',
        'Ranged (Bow)',
      ],
    },
    'estalian-nom': {
      name: 'Estalian',
      skills: [
        'Athletics',
        'Bribery',
        'Charm',
        'Consume Alcohol',
        'Entertain (Storytelling)',
        'Gossip',
        'Language (Bretonnian)',
        'Language (Tilean)',
        'Language (Arabyan)',
        'Lore (Region)',
        'Perform (Jota)',
        'Sleight of Hand',
      ],
    },
    'indan-nom': {
      skills: [
        'Animal Care',
        'Charm',
        'Cool',
        'Endurance',
        'Gossip',
        'Haggle',
        'Language (Arabyan)',
        'Language (Cathayan)',
        'Language (Wastelander)',
        'Lore (Kingdom)',
        'Melee (Basic)',
        'Ranged (Throwing)',
      ],
    },
    'gospodar-nom': {
      skills: [
        'Animal Care',
        'Charm Animal',
        'Cool',
        'Evaluate',
        'Gossip',
        'Haggle',
        'Language (Wastelander)',
        'Language (Norse)',
        'Language (Ungol)',
        'Lore (Kislev)',
        'Melee (Basic)',
        'Ranged (Bow)',
        'Ride (Horse)',
      ],
    },
    'ungol-nom': {
      skills: [
        'Animal Care',
        'Charm Animal',
        'Cool',
        'Drive',
        'Gossip',
        'Haggle',
        'Intimidate',
        'Language (Gospodarinyi)',
        'Lore (Kislev)',
        'Melee (Basic)',
        'Outdoor Survival',
        'Ranged (Bow)',
      ],
    },
    'nipponese-nom': {
      skills: [
        'Charm',
        'Cool',
        'Gossip',
        'Haggle',
        'Language (Cathayan)',
        'Language (Wastelander)',
        'Leadership',
        'Lore (Nippon)',
        'Melee (Basic)',
        'Ranged (Bow)',
        'Sail',
        'Swim',
      ],
    },
    'norscan-nom': {
      skills: [
        'Athletics',
        'Climb',
        'Consume Alcohol',
        'Cool',
        'Endurance',
        'Intimidate',
        'Lore (Norsca)',
        'Melee (Basic)',
        'Melee (Two-Handed)',
        'Outdoor Survival',
        'Perception',
        'Sail',
        'Swim',
      ],
    },
    'southlander-nom': {
      skills: [
        'Animal Care',
        'Athletics',
        'Climb',
        'Cool',
        'Endurance',
        'Gossip',
        'Language (Arabyan)',
        'Language (Cathayan)',
        'Melee (Polearm)',
        'Navigation',
        'Outdoor Survival',
        'Perception',
        'Ranged (Throwing)',
      ],
    },
    'strigany-nom': {
      skills: [
        'Animal Care',
        'Charm Animal',
        'Charm',
        'Entertain (Sing)',
        'Entertain (Storytelling)',
        'Gossip',
        'Haggle',
        'Language (Any)',
        'Lore (Local)',
        'Lore (Spirits)',
        'Perform (Any)',
        'Play (Any)',
        'Ride (Horse)',
      ],
    },
    'tilean-nom': {
      skills: [
        'Art (Any)',
        'Bribery',
        'Charm',
        'Consume Alcohol',
        'Entertain (Storytelling)',
        'Gossip',
        'Language (Estalian)',
        'Language (Bretonnian)',
        'Lore (Politics)',
        'Lore (City State)',
        'Sail',
        'Sleight of Hand',
      ],
    },
    'westerlander-nom': {
      skills: [
        'Bribery',
        'Charm',
        'Cool',
        'Evaluate',
        'Gossip',
        'Haggle',
        'Language (Arabyan)',
        'Language (Bretonnian)',
        'Language (Cathayan)',
        'Language (Nipponese)',
        'Language (Estalian)',
        'Language (Tilean)',
        'Lore (Westerland)',
        'Sail',
        'Trade (Any)',
      ],
    },
    reiklander: {
      skills: [
        'Animal Care',
        'Charm',
        'Cool',
        'Evaluate',
        'Gossip',
        'Haggle',
        'Language (Bretonnian)',
        'Language (Wastelander)',
        'Leadership',
        'Lore (Reikland)',
        'Melee (Basic)',
        'Ranged (Bow)',
      ],
    },
    middenheimer: {
      skills: [
        'Bribery',
        'Charm',
        'Cool',
        'Entertain (Any)',
        'Evaluate',
        'Gossip',
        'Haggle',
        'Leadership',
        'Lore (Middenheim)',
        'Melee (Basic)',
        'Ranged (Bow)',
        'Trade (any one)',
      ],
    },
    middenlander: {
      skills: [
        'Animal Care',
        'Cool',
        'Evaluate',
        'Gossip',
        'Haggle',
        'Intimidate',
        'Language (Wastelander)',
        'Leadership',
        'Lore (Middenland)',
        'Melee (Basic)',
        'Outdoor Survival',
        'Ranged (Bow)',
      ],
    },
    nordlander: {
      skills: [
        'Consume Alcohol',
        'Evaluate',
        'Gossip',
        'Haggle',
        'Language (Norse)',
        'Language (Wastelander)',
        'Lore (Nordland)',
        'Melee (Basic)',
        'Ranged (Bow)',
        'Sail (Any)',
        'Swim',
        'Trade (any one)',
      ],
    },
  },
  dwarf: {
    greydwarf: {
      skills: [
        'Consume Alcohol',
        'Cool',
        'Endurance',
        'Entertain (Storytelling)',
        'Evaluate',
        'Intimidate',
        'Language (Khazalid)',
        'Lore (Dwarfs)',
        'Lore (Geology)',
        'Lore (Metallurgy)',
        'Melee (Basic)',
        'Trade (Any)',
      ],
    },
    norsedwarf: {
      skills: [
        'Consume Alcohol',
        'Cool',
        'Endurance',
        'Intimidate',
        'Language (Khazalid) ',
        'Language (Norse)',
        'Lore (Chaos)',
        'Lore (Dwarfs)',
        'Lore (Norsca)',
        'Mele (Basic)',
        'Melee (Two-Handed)',
        'Trade (Any)',
      ],
    },
    imperialdwarf: {
      skills: [
        'Charm',
        'Consume Alcohol',
        'Cool',
        'Entertain (Storytelling)',
        'Evaluate',
        'Haggle',
        'Language (Bretonnian)',
        'Language (Estalian)',
        'Language (Tilean)',
        'Language (Khazalid)',
        'Lore (Dwarfs)',
        'Lore (Empire)',
        'Lore (Local)',
        'Melee (Basic)',
        'Trade (Any)',
      ],
    },
  },
  halfling: {
    ashfield: {
      skills: [
        'Charm',
        'Consume Alcohol',
        'Haggle',
        'Lore (Reikland)',
        'Sleight of Hand',
        'Stealth (Any)',
        'Trade (Cook)',
        'Cool',
        'Intuition',
        'Language (Mootish)',
        'Ranged (any)',
      ],
    },
    brambledown: {
      skills: [
        'Charm',
        'Consume Alcohol',
        'Haggle',
        'Lore (Reikland)',
        'Sleight of Hand',
        'Stealth (Any)',
        'Trade (Cook)',
        'Language (Mootish) ',
        'Navigation',
        'Outdoor Survival ',
        'Swim',
      ],
    },
    brandysnap: {
      skills: [
        'Charm',
        'Consume Alcohol',
        'Haggle',
        'Lore (Reikland)',
        'Sleight of Hand',
        'Stealth (Any)',
        'Trade (Cook)',
        'Animal Care',
        'Gamble',
        'Language (Mootish)',
        'Lore (Herbs)',
      ],
    },
    hayfoot: {
      skills: [
        'Charm',
        'Consume Alcohol',
        'Haggle',
        'Lore (Reikland)',
        'Sleight of Hand',
        'Stealth (Any)',
        'Trade (Cook)',
        'Gamble',
        'Haggle',
        'Evaluate',
        'Language (Mootish)',
      ],
    },
    hollyfoot: {
      skills: [
        'Charm',
        'Consume Alcohol',
        'Haggle',
        'Lore (Reikland)',
        'Sleight of Hand',
        'Stealth (Any)',
        'Trade (Cook)',
        'Bribery',
        'Haggle',
        'Gossip',
        'Language (Mootish)',
      ],
    },
    'hayfoot—hollyfoot': {
      skills: [
        'Charm',
        'Consume Alcohol',
        'Haggle',
        'Lore (Reikland)',
        'Sleight of Hand',
        'Stealth (Any)',
        'Trade (Cook)',
        'Bribery',
        'Haggle',
        'Gossip',
        'Language (Mootish)',
      ],
    },
    'hayfoot-hollyfoot': {
      skills: [
        'Charm',
        'Consume Alcohol',
        'Haggle',
        'Lore (Reikland)',
        'Sleight of Hand',
        'Stealth (Any)',
        'Trade (Cook)',
        'Bribery',
        'Haggle',
        'Gossip',
        'Language (Mootish)',
      ],
    },
    lostpockets: {
      skills: [
        'Charm',
        'Consume Alcohol',
        'Haggle',
        'Lore (Reikland)',
        'Sleight of Hand',
        'Stealth (Any)',
        'Trade (Cook)',
        'Endurance',
        'Gamble',
        'Gossip',
        'Intuition',
      ],
    },
    lowhaven: {
      skills: [
        'Charm',
        'Consume Alcohol',
        'Haggle',
        'Lore (Reikland)',
        'Sleight of Hand',
        'Stealth (Any)',
        'Trade (Cook)',
        'Bribery',
        'Haggle',
        'Intimidate',
        'Language (Mootish)',
      ],
    },
    rumster: {
      skills: [
        'Charm',
        'Consume Alcohol',
        'Haggle',
        'Lore (Reikland)',
        'Sleight of Hand',
        'Stealth (Any)',
        'Trade (Cook)',
        'Endurance',
        'Gossip',
        'Haggle',
        'Language (Mootish)',
      ],
    },
    skelfsider: {
      skills: [
        'Charm',
        'Consume Alcohol',
        'Haggle',
        'Lore (Reikland)',
        'Sleight of Hand',
        'Stealth (Any)',
        'Trade (Cook)',
        'Endurance',
        'Gamble',
        'Gossip',
        'Language (Mootish)',
      ],
    },
    thorncobble: {
      skills: [
        'Charm',
        'Consume Alcohol',
        'Haggle',
        'Lore (Reikland)',
        'Sleight of Hand',
        'Stealth (Any)',
        'Trade (Cook)',
        'Gossip',
        'Leadership',
        'Lore (Heraldry)',
        'Language (Mootish)',
      ],
    },
    tumbleberry: {
      skills: [
        'Charm',
        'Consume Alcohol',
        'Haggle',
        'Lore (Reikland)',
        'Sleight of Hand',
        'Stealth (Any)',
        'Trade (Cook)',
        'Gossip',
        'Haggle',
        'Lore (Any)',
        'Language (Mootish)',
      ],
    },
  },
};

export const subSpeciesTalents = {
  human: {
    'averlander-nom': {
      talents: [
        'Doomed, Hatred (Greenskins)',
        'Etiquette (Dwarves), @Table[talents]{Additional Random Talent}',
        'Sharp, Suave',
        2,
      ],
    },
    'hochlander-nom': {
      talents: ['Doomed, Rover', 'Marksman, Sharp', 3],
    },
    'ostermarker-nom': {
      talents: [
        'Doomed, @Table[talents]{Additional Random Talent}',
        'Marksman, Coolheaded',
        3,
      ],
    },
    'ostlander-nom': {
      talents: [
        'Doomed, @Table[talents]{Additional Random Talent}',
        'Very Resilient, Stone Soup',
        3,
      ],
    },
    'stirlander-nom': {
      talents: [
        'Doomed, @Table[talents]{Additional Random Talent}',
        'Nimble Fingered, Suave',
        3,
      ],
    },
    'sylvanian-nom': {
      talents: ['Coolheaded, Sharp', 'Flee!', 3],
    },
    'talabeclander-nom': {
      talents: ['Doomed, Accurate Shot', 'Marksman, Savvy', 3],
    },
    'wissenlander-nom': {
      talents: ['Doomed', 'Coolheaded, Savvy', 3],
    },
    'albionite-nom': {
      talents: [
        'Resistance (Mutation)',
        'Stone Soup',
        'Strider (Marshes)',
        'Warrior Born',
        'Very Strong, Very Resilient',
      ],
    },
    'arabyan-nom': {
      talents: [
        'Nimble Fingered, Suave',
        'Read/Write, Craftsman (Any)',
        'Resistance (Heat), Strider (Deserts)',
        '@Compendium[nations-of-mankind-wfrp4e.journalentries-nom.siN4XGTmiQTSMBuX]{City State Trait (Any)}',
      ],
    },
    'breton-noble-nom': {
      talents: [
        'Noble Blood',
        'Read/Write',
        'Suave, Warrior Born',
        '@Compendium[nations-of-mankind-wfrp4e.journalentries-nom.siN4XGTmiQTSMBuX]{Dukedom Trait (Any)}',
      ],
    },
    'breton-lowborn-nom': {
      talents: [
        'Nimble Fingered, Very Resilient',
        'Stone Soup',
        'Strong Back',
        '@Compendium[nations-of-mankind-wfrp4e.journalentries-nom.siN4XGTmiQTSMBuX]{Dukedom Trait (Any)}',
      ],
    },
    'cathayan-nom': {
      talents: [
        'Coolheaded, Savvy',
        'Read/Write, Linguistics',
        '@Compendium[nations-of-mankind-wfrp4e.journalentries-nom.siN4XGTmiQTSMBuX]{Provincial Trait (Any)}',
      ],
    },
    'estalian-nom': {
      talents: [
        'Nose for Trouble',
        'Savvy, Suave',
        '@Compendium[nations-of-mankind-wfrp4e.journalentries-nom.siN4XGTmiQTSMBuX]{Region Trait (Any)}',
      ],
    },
    'indan-nom': {
      talents: [
        'Lightning Reflexes, Suave',
        'Luck',
        'Resistance (Heat), @Table[talents]{One Additional Random Talent}',
        '@Compendium[nations-of-mankind-wfrp4e.journalentries-nom.siN4XGTmiQTSMBuX]{Kingdom Trait (Any)}',
      ],
    },
    'gospodar-nom': {
      talents: [
        'Resistance (Cold)',
        'Suave, Savvy',
        'Very Strong, Warrior Born',
        '@Compendium[nations-of-mankind-wfrp4e.journalentries-nom.siN4XGTmiQTSMBuX]{Provincial Trait (Any)}',
      ],
    },
    'ungol-nom': {
      talents: [
        'Hardy, @Table[talents]{One Additional Random Talent}',
        'Resistance (Cold)',
        'Marksman, Very Resilient',
        '@Compendium[nations-of-mankind-wfrp4e.journalentries-nom.siN4XGTmiQTSMBuX]{Provincial Trait (Any)}',
      ],
    },
    'nipponese-nom': {
      talents: [
        'Sixth Sense',
        'Warrior Born, Sharp',
        '@Compendium[nations-of-mankind-wfrp4e.journalentries-nom.siN4XGTmiQTSMBuX]{Clan Trait (Any)}',
      ],
    },
    'norscan-nom': {
      talents: [
        'Night Vision',
        'Resistance (Cold)',
        'Very Strong, Warrior Born',
        '@Compendium[nations-of-mankind-wfrp4e.journalentries-nom.siN4XGTmiQTSMBuX]{Tribe Trait (Any)}, @Table[talents]{Two Additional Random Talents}',
      ],
    },
    'southlander-nom': {
      talents: [
        'Lightning Reflexes, Sprinter',
        'Strong Legs, @Table[talents]{One Additional Random Talent}',
        '@Compendium[nations-of-mankind-wfrp4e.journalentries-nom.siN4XGTmiQTSMBuX]{Tribe Trait (Any)}',
      ],
    },
    'strigany-nom': {
      talents: [
        'Animal Affinity, Perfect Pitch',
        'Seasoned Traveler',
        'Sharp, Suave',
        2,
      ],
    },
    'tilean-nom': {
      talents: [
        'Gregarious, @Table[talents]{One Additional Random Talent}',
        'Read/Write, @Table[talents]{One Additional Random Talent}',
        'Sharp, Suave',
        '@Compendium[nations-of-mankind-wfrp4e.journalentries-nom.siN4XGTmiQTSMBuX]{City-State Trait (Any)}',
      ],
    },
    'westerlander-nom': {
      talents: ['Briber, Deal Maker', 'Savvy, Suave', 3],
    },
    reiklander: {
      talents: ['Doomed', 'Savvy, Suave', 3],
    },
    middenheimer: {
      talents: ['Doomed', 'Etiquette (choose group), Strong Back', 3],
    },
    middenlander: {
      talents: [
        'Doomed, @Table[talents]{Additional Random Talent}',
        'Menacing, Warrior Born',
        3,
      ],
    },
    nordlander: {
      talents: [
        'Doomed, @Table[talents]{Additional Random Talent}',
        'Fisherman, Rover',
        'Stout-hearted, Very Resilient',
        2,
      ],
    },
  },
  dwarf: {
    karakdwarf: {},
    greydwarf: {
      talents: [
        'Craftsman (Any), Linguistics',
        'Night Vision',
        'Magic Resistance',
        'Nimble Fingered, Read/Write',
        'Sixth Sense, Sturdy',
      ],
    },
    norsedwarf: {
      talents: [
        'Magic Resistance',
        'Night Vision',
        'Pure Soul, Read/Write',
        'Resistance (Mutation), Robust',
        'Stout-hearted, Sturdy',
      ],
    },
    imperialdwarf: {
      talents: ['Magic Resistance', 'Night Vision', 'Read/Write, Sturdy', 2],
    },
  },
  welf: {
    harioth: {
      talents: [
        'Acute Sense (WFRP4NPCGEN.sight)',
        'Hardy, Second Sight',
        'Night Vision',
        'Read/Write, Very Resilient',
        'Rover',
        'Youngblood',
        0,
      ],
    },
    toriour: {},
    faniour: {},
  },
  halfling: {
    ashfield: {
      talents: [
        'Acute Sense (WFRP4NPCGEN.taste)',
        'Night Vision',
        'Resistance (Chaos)',
        'Small',
        'Acute Sense (WFRP4NPCGEN.sight), Etiquette (Soldiers)',
        1,
      ],
    },
    brambledown: {
      talents: [
        'Acute Sense (WFRP4NPCGEN.taste)',
        'Night Vision',
        'Resistance (Chaos)',
        'Small',
        'Gregarious, Seasoned Traveller',
        1,
      ],
    },
    brandysnap: {
      talents: [
        'Acute Sense (WFRP4NPCGEN.taste)',
        'Night Vision',
        'Resistance (Chaos)',
        'Small',
        'Craftsman (Farmer), Sturdy',
        1,
      ],
    },
    hayfoot: {
      talents: [
        'Acute Sense (WFRP4NPCGEN.taste)',
        'Night Vision',
        'Resistance (Chaos)',
        'Small',
        'Dealmaker, Etiquette (Guidlers)',
        1,
      ],
    },
    hollyfoot: {
      talents: [
        'Acute Sense (WFRP4NPCGEN.taste)',
        'Night Vision',
        'Resistance (Chaos)',
        'Small',
        'Craftsman (Any), Nimble Fingered',
        1,
      ],
    },
    'hayfoot—hollyfoot': {
      talents: [
        'Acute Sense (WFRP4NPCGEN.taste)',
        'Night Vision',
        'Resistance (Chaos)',
        'Small',
        'Argumentative, Numismatics',
        1,
      ],
    },
    'hayfoot-hollyfoot': {
      talents: [
        'Acute Sense (WFRP4NPCGEN.taste)',
        'Night Vision',
        'Resistance (Chaos)',
        'Small',
        'Argumentative, Numismatics',
        1,
      ],
    },
    lostpockets: {
      talents: [
        'Acute Sense (WFRP4NPCGEN.taste)',
        'Night Vision',
        'Resistance (Chaos)',
        'Small',
        'Hardy, Stone Soup',
        1,
      ],
    },
    lowhaven: {
      talents: [
        'Acute Sense (WFRP4NPCGEN.taste)',
        'Night Vision',
        'Resistance (Chaos)',
        'Small',
        'Criminal, Etiquette (Criminal or Guilders)',
        1,
      ],
    },
    rumster: {
      talents: [
        'Acute Sense (WFRP4NPCGEN.taste)',
        'Night Vision',
        'Resistance (Chaos)',
        'Small',
        'Craftsman (Cook), Dealmaker',
        1,
      ],
    },
    skelfsider: {
      talents: [
        'Acute Sense (WFRP4NPCGEN.taste)',
        'Night Vision',
        'Resistance (Chaos)',
        'Small',
        'Beneath Notice, Etiquette (Servants)',
        1,
      ],
    },
    thorncobble: {
      talents: [
        'Acute Sense (WFRP4NPCGEN.taste)',
        'Night Vision',
        'Resistance (Chaos)',
        'Small',
        'Etiquette (Nobles or Scholars), Read/Write',
        1,
      ],
    },
    tumbleberry: {
      talents: [
        'Acute Sense (WFRP4NPCGEN.taste)',
        'Night Vision',
        'Resistance (Chaos)',
        'Small',
        'Etiquette (Burghers or Guilders), Read/Write',
        1,
      ],
    },
  },
};
